name: Sync Fork

on:
  schedule:
    - cron: '0 0 */3 * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
          
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: 2
          keep_minimum_runs: 0  
          
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: Yidadaa
          repo: ChatGPT-Next-Web
          base: main
          head: main
