name: Sync Fork

on:
  schedule:
    - cron: '* */3 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: Yidadaa
          base: main
          head: main
          
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: 1
          keep_minimum_runs: 0  
